"""UniReg regulation parser."""

from unireg.citations import Citation, CitationGenerator
from unireg.cleaning import DocumentCleaner
from unireg.exporters import JSONExporter, MarkdownExporter
from unireg.loaders import PDFLoader
from unireg.models import (
    AmendmentEvent,
    AmendmentEventType,
    Appendix,
    Article,
    Chapter,
    Clause,
    IncompletenessFlag,
    IncompletenessType,
    Item,
    NodeType,
    ProvisionStatus,
    Reference,
    ReferenceStatus,
    ReferenceType,
    Regulation,
    RegulationDocument,
    Section,
    SourceSpan,
    SubItem,
    Table,
)
from unireg.parser import (
    MetadataWarning,
    RegulationMetadata,
    RegulationMetadataNormalizer,
    RegulationParser,
)
from unireg.projections import (
    BM25Document,
    GraphEdge,
    GraphEdgeType,
    GraphNode,
    ProjectionBuilder,
    ProjectionSet,
    VectorDocument,
)

__all__ = [
    "AmendmentEvent",
    "AmendmentEventType",
    "Appendix",
    "Article",
    "BM25Document",
    "Chapter",
    "Citation",
    "CitationGenerator",
    "Clause",
    "DocumentCleaner",
    "GraphEdge",
    "GraphEdgeType",
    "GraphNode",
    "IncompletenessFlag",
    "IncompletenessType",
    "Item",
    "JSONExporter",
    "MarkdownExporter",
    "MetadataWarning",
    "NodeType",
    "PDFLoader",
    "ProjectionBuilder",
    "ProjectionSet",
    "ProvisionStatus",
    "Reference",
    "ReferenceStatus",
    "ReferenceType",
    "Regulation",
    "RegulationDocument",
    "RegulationMetadata",
    "RegulationMetadataNormalizer",
    "RegulationParser",
    "Section",
    "SourceSpan",
    "SubItem",
    "Table",
    "VectorDocument",
]
